name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download Homer release
        run: |
          wget https://github.com/bastienwirtz/homer/releases/latest/download/homer.zip
          unzip homer.zip
          rm homer.zip
      
      - name: Download assets
        uses: actions/checkout@v4
      
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v4
      
      - name: Upload artifact to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
